name: DevOps IBM Bus Main

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        description: 'Nombre del proyecto o Aplicación Principal del BUS a procesar'
        required: true
        type: string
      SERVER_NAME:
        description: 'Nombre del servidor de integración, al que se realizara el despliegue del empaquetado .bar'
        required: true
        type: string
      LIBRARY_NAME:
        description: 'Librería o Librerías que se desea incluir en el empaquetado, separados por espacio ejemplo: LibraryName1 LibraryName2 .... LibraryNamen'
        required: false
        type: string
      RUN_CREATE_BAR:
        description: 'Ejecutar mqsicreatebar para compilar conjuntos de mensajes y código Java, valores permitidos (true, false)'
        required: false
        type: string
      OVERRIDE_PROPERTIES:
        description: 'Lista de propiedades que requieren hacer override al empaquetado bar'
        required: false
        type: string
      REPLICAR:
        description: 'Indica si el despliegue se replicara el los Nodos de Integración, (true or false)'
        required: false
        type: boolean
  
env:
  PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
  LIBRARY_NAME: ${{ inputs.LIBRARY_NAME }}
  RUN_CREATE_BAR: ${{ inputs.RUN_CREATE_BAR }}
  SERVER_NAME: ${{ inputs.SERVER_NAME }}
  OVERRIDE_PROPERTIES: ${{ inputs.OVERRIDE_PROPERTIES }}
  CONNECTION_BROKER: ${{ secrets.INT_BUS_CONNECTION_BROKER_PROD }}
  CONNECTION_BROKER2: ${{ secrets.INT_BUS_CONNECTION_BROKER_PROD2 }}
  PACKAGE_SCRIPT_PATH: ${{ secrets.INT_BUS_SCRIPT_PATH_PACKAGE }}
  DEPLOY_SCRIPT_PATH: ${{ secrets.INT_BUS_SCRIPT_PATH_DEPLOY }}
  CLEAN_SCRIPT_PATH: ${{ secrets.INT_BUS_SCRIPT_PATH_CLEAN }}
  

jobs:
  packageAndDeploy:
    runs-on: [self-hosted, linux, x64, BUS]    
    timeout-minutes: 5 
    environment: main
    steps:
      - name: Descargar Repositorio al Runner
        uses: actions/checkout@v3
      - name: Generar empaquetado bar
        run: |
          chmod +x $PACKAGE_SCRIPT_PATH 
          $PACKAGE_SCRIPT_PATH
      - name: Cargar empaquetado bar a github
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ github.workspace }}/bar/${{ env.PROJECT_NAME }}.bar   
      - name: Realizar despliegue al Nodo de Integración
        run: |
          chmod +x $DEPLOY_SCRIPT_PATH 
          $DEPLOY_SCRIPT_PATH
  deploy2:
    if: ${{ inputs.REPLICAR }}
    runs-on: [self-hosted, linux, x64, BUS]
    timeout-minutes: 5
    needs: packageAndDeploy
    environment: main2
    steps:
      - name: Realizar despliegue a IBM Integration Bus
        run: |
          chmod +x $DEPLOY_SCRIPT_PATH 
          $DEPLOY_SCRIPT_PATH
        env:
          CONNECTION_BROKER: ${{ env.CONNECTION_BROKER2 }}
  clean:
    runs-on: [self-hosted, linux, x64, BUS]
    timeout-minutes: 5
    if: ${{ always() }}
    needs: deploy2
    steps:
      - name: Remover directorio y archivos del respositorio
        run: |
          chmod +x $CLEAN_SCRIPT_PATH 
          $CLEAN_SCRIPT_PATH
