name: DevOps IBM Bus Main

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        description: 'Nombre del proyecto o Aplicación Principal del BUS a procesar'
        required: true
        type: string
      INTEGRATION_NODES:
        description: 'Alias de los Nodos de Integración, al que se realizara el despliegue del empaquetado .bar. Cada Nodo de integración debe ser separado por espacio ejemplo: Nodo01 Nodo02, ... Nodon'
        required: true
        type: string
      SERVER_NAME:
        description: 'Nombre del servidor de integración, al que se realizara el despliegue del empaquetado .bar'
        required: true
        type: string      
      LIBRARY_NAME:
        description: 'Librería o Librerías que se desea incluir en el empaquetado, separados por espacio ejemplo: LibraryName1 LibraryName2 .... LibraryNamen'
        required: false
        type: string
      RUN_CREATE_BAR:
        description: 'Ejecutar mqsicreatebar para compilar conjuntos de mensajes y código Java, valores permitidos (true, false)'
        required: false
        type: string
      MAPS_AND_SCHEMAS:
        description: 'Habilitar la compilación de mapas y esquemas, valores permitidos (true, false)'
        required: false
        type: string
      OVERRIDE_PROPERTIES:
        description: 'Lista de propiedades que requieren hacer override al empaquetado bar'
        required: false
        type: string
  
env:
  PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
  INTEGRATION_NODES: ${{ inputs.INTEGRATION_NODES }}
  SERVER_NAME: ${{ inputs.SERVER_NAME }}
  LIBRARY_NAME: ${{ inputs.LIBRARY_NAME }}
  RUN_CREATE_BAR: ${{ inputs.RUN_CREATE_BAR }}
  MAPS_AND_SCHEMAS: ${{ inputs.MAPS_AND_SCHEMAS }}  
  OVERRIDE_PROPERTIES: ${{ inputs.OVERRIDE_PROPERTIES }}
  PACKAGE_SCRIPT_PATH: ${{ secrets.INT_BUS_SCRIPT_PATH_PACKAGE }}
  DEPLOY_SCRIPT_PATH: ${{ secrets.INT_BUS_SCRIPT_PATH_DEPLOY }}
  CLEAN_SCRIPT_PATH: ${{ secrets.INT_BUS_SCRIPT_PATH_CLEAN }}
  NODE_PROD_01: ${{ secrets.INT_BUS_CB_PROD01_ITESM }}
  NODE_PROD_02: ${{ secrets.INT_BUS_CB_PROD02_ITESM }}
  NODE_PRODMQ_01: ${{ secrets.INT_BUS_CB_PRODMQ01_ITESM }}
  NODE_PRODMQ_02: ${{ secrets.INT_BUS_CB_PRODMQ02_ITESM }}
  WF_ENVIRONMENT: main

jobs:
  packageAndDeploy:
    runs-on: [self-hosted, linux, x64, BUS]    
    timeout-minutes: 5 
    environment: main
    steps:
      - name: Descargar Repositorio al Runner
        uses: actions/checkout@v3
        with:
          ref: main_ace
      - name: Generar empaquetado bar
        run: |
          chmod +x $PACKAGE_SCRIPT_PATH 
          $PACKAGE_SCRIPT_PATH
      - name: Cargar empaquetado bar a github
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ github.workspace }}/bar/${{ env.PROJECT_NAME }}.bar   
      - name: Realizar despliegue al Nodo de Integración
        run: |
          chmod +x $DEPLOY_SCRIPT_PATH 
          $DEPLOY_SCRIPT_PATH
  clean:
    runs-on: [self-hosted, linux, x64, BUS]
    timeout-minutes: 5
    if: ${{ always() }}
    needs: packageAndDeploy
    steps:
      - name: Remover directorio y archivos del respositorio
        run: |
          chmod +x $CLEAN_SCRIPT_PATH 
          $CLEAN_SCRIPT_PATH
